# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop"  ]
  pull_request:
    branches: [ "main" , "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: hospify_appointment_system
      DB_USER: postgres
      DB_PASSWORD: password

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: maven

      - name: Set up PostgreSQL
        uses: docker://postgres:13-alpine
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_DATABASE }}
        with:
          args: >
            -p ${{ env.DB_PORT }}:5432
            -e POSTGRES_USER
            -e POSTGRES_PASSWORD
            -e POSTGRES_DB
            --name postgres
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 3
            -d postgres:13-alpine

      - name: Wait for PostgreSQL to start
        run: docker exec postgres sh -c 'while ! pg_isready -U ${{ env.DB_USER }} -d ${{ env.DB_DATABASE }} -h localhost -p ${{ env.DB_PORT }}; do sleep 1; done;'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
