# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop"  ]
  pull_request:
    branches: [ "main" , "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    strategy:
      matrix:
        java-version: [17]

#    env:
#      DB_DATABASE: hivedb
#      DB_USER: root
#      DB_PASSWORD: root

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: maven
          
          
      - name: Set up Postgres
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE DATABASE hospify_appointment_system;"
          sudo -u postgres psql -c "CREATE USER postgres WITH ENCRYPTED PASSWORD '123';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE hospify_appointment_system TO postgres;"


      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
