name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  POSTGRES_DB: hospify_appointment_system
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 123

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: hospify_appointment_system
          POSTGRES_USER: postgres
          POSTGRES_DB: 123
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Install dependencies and run tests
      run: mvn -B verify
        
    - name: Setup PostgreSQL database
      run: |
        psql --host=localhost --port=5432 --username=$POSTGRES_USER --password=$POSTGRES_PASSWORD --dbname=$POSTGRES_DB --command="CREATE DATABASE hospify_appointment_system;"
        
    - name: Set application properties
      run: |
        echo "spring.datasource.url=jdbc:postgresql://localhost:5432/hospify" >> src/main/resources/application.properties
        echo "spring.datasource.username=$POSTGRES_USER" >> src/main/resources/application.properties
        echo "spring.datasource.password=$POSTGRES_PASSWORD" >> src/main/resources/application.properties
